name: Build and Publish Caddy with DNS plugin (DigitalOcean) Image

on:
  workflow_dispatch:
    inputs:
      image_name:
        description: 'Image name (e.g. ghcr.io/OWNER/REPO/caddy-digitalocean)'
        required: true
        default: 'ghcr.io/null-icicle/hypnotic-mist/caddy-digitalocean'
      docker_file_dir:
        description: 'Directory containing the Dockerfile'
        required: true
        default: './infra/docker/caddy-digitalocean'
  schedule:
    - cron: '15 23 * * *' # every 24h

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
      REGISTRY: ghcr.io
      DOCKERFILE_DIR: ${{ github.event.inputs.docker_file_dir || './infra/docker/caddy-digitalocean' }}
      IMAGE_NAME: ${{ github.event.inputs.image_name || 'ghcr.io/null-icicle/hypnotic-mist/caddy-digitalocean' }}
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Caddy version
        id: caddy_version
        run: |
          version=$(curl -s https://api.github.com/repos/caddyserver/caddy/releases/latest | grep 'tag_name' | cut -d\" -f4 | sed 's/v//')
          major=$(echo "$version" | cut -d. -f1)
          minor=$(echo "$version" | cut -d. -f2)
          echo "version=$version" >> $GITHUB_OUTPUT
          echo "major=$major" >> $GITHUB_OUTPUT
          echo "minor=$minor" >> $GITHUB_OUTPUT

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ${{ env.DOCKERFILE_DIR }}
          file: ${{ env.DOCKERFILE_DIR }}/Dockerfile
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:${{ steps.caddy_version.outputs.version }}
            ${{ env.IMAGE_NAME }}:${{ steps.caddy_version.outputs.major }}
            ${{ env.IMAGE_NAME }}:${{ steps.caddy_version.outputs.major }}.${{ steps.caddy_version.outputs.minor }}
          build-args: |
            CADDY_VERSION=${{ steps.caddy_version.outputs.version }}
