name: Build and Publish PocketBase Image

on:
  workflow_dispatch:
    inputs:
      image_name:
        description: 'Image name (e.g. ghcr.io/OWNER/REPO/pocketbase)'
        required: true
        default: 'ghcr.io/null-icicle/hypnotic-mist/pocketbase'
  schedule:
    - cron: '15 23 * * *' # every 24h

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
      REGISTRY: ghcr.io
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract PocketBase version
        id: pb_version
        run: |
          version=$(curl -s https://api.github.com/repos/pocketbase/pocketbase/releases/latest | grep 'tag_name' | cut -d\" -f4 | sed 's/v//')
          major=$(echo "$version" | cut -d. -f1)
          echo "version=$version" >> $GITHUB_OUTPUT
          echo "major=$major" >> $GITHUB_OUTPUT

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./infra/docker/pocketbase
          file: ./infra/docker/pocketbase/Dockerfile
          push: true
          tags: |
            ${{ github.event.inputs.image_name }}:${{ steps.pb_version.outputs.version }}
            ${{ github.event.inputs.image_name }}:${{ steps.pb_version.outputs.major }}
            ${{ github.event.inputs.image_name }}:latest
